<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>B BOX</name>
   <tag></tag>
   <elementGuidId>61cfbde2-29c2-4382-bbfb-ab0a304bf204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-picAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-picAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>935e6061-d665-4508-b2de-c3a5d2f9b7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>3fe80c06-d48c-4d74-a091-abf79d9cde35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-picAdd-container</value>
      <webElementGuid>987d1c9f-23d7-481a-98ba-fbc95d401c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose PIC --</value>
      <webElementGuid>a4b6c25b-1e79-4131-8136-311169180532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-picAdd-container&quot;)</value>
      <webElementGuid>05cbe5df-8c28-4521-bc54-8d3d68fe54be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-picAdd-container']</value>
      <webElementGuid>7361b1c5-e3a3-41b3-a1e9-61568c82d2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/span/span/span/span</value>
      <webElementGuid>73378ada-9258-444e-bb9f-57976f3498ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>7936e942-e887-46ef-b2d3-9793a9a02c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-picAdd-container' and (text() = '-- Choose PIC --' or . = '-- Choose PIC --')]</value>
      <webElementGuid>000b9feb-90a5-4cd9-9e29-2c8a02f0d433</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
