<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Branch List PIC</name>
   <tag></tag>
   <elementGuidId>0cb8e282-3bbf-41f6-b1c2-fc09b96eba41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-picAdd-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-picAdd-results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>9166b227-1548-4f0f-b254-4db622998f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>ece1bab6-bd53-454f-93c4-7226be7473f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tree</value>
      <webElementGuid>9b16a4a8-1cdc-484b-a434-f73e3f285a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-picAdd-results</value>
      <webElementGuid>e82ee560-27b0-4d53-8fb5-bf3a4c5dd979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa0b9e42-2d65-4cee-b3cb-0cfbde0218c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d967537-e22b-4d8e-8560-9dddafc3ec16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eric - igloanam - igloFachri eKreasi - igloRaihan - IndocyberYoga Wiranda - igloAdmin Indocyber - indocyberdevapi - igloakun dev - indocyberFachri iglo - igloStephen Strange - igloAkun Demo - demoadmin - igloKMS - kmsMaya Nurmalasari - democobaja - igloPUTRA DWI JULIANTO - igloAndre - indocyberakun - indocyberfurqan - igloBruce Banner - iglotabita iglo - igloeric - iglojean - jeaneric - igloErlan S - hahahihiBeby Romeo - demoDummy 02 - indocyberTabita - igloEric Yop - igloRobert Downey - igloBerliandika - indocyberAdmin Indocyber - igloKMS Indocyber - iglotest - igloEric Cantona - igloanam - igloTony Stark - igloshafrizal - iglotasya 2 - igloandre berliansyah - igloEric Yop - igloEric - iglocobaja - iglofurqan tes - ekreasicoba - igloTabita Iglo - igloAdmin - igloNovian Faisal - igloAdmin - igloAkun Indocyber - indocyberABBAS SALEH - iglofurqannn - igloTes Register Error - ahmad agus - 4hm4dTabita Id - demoEpul - igloeric - igloCoba register pake mobile - igloUpturn - DemoEmber - indocyberSahid Test - igloeKreasi - trialeric - igloDemo - fachri iglo - iglotestgalang - igloEGG - iglotasya - iglouser_test - igloEl Fachri - fachri ekf - igloFurqan AWJ - indocybersylvia - igloUser Demo - demofurqann - igloSahid R - iglofurqan - igloerlan - hahahihitestgalang - igloEric Yop - iglotasya - demoAndre Berlian - iglo</value>
      <webElementGuid>2f409769-513e-4242-9ec2-aa44451a0997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-picAdd-results&quot;)</value>
      <webElementGuid>f6fecc87-3845-4288-9e76-43c02a497e67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-picAdd-results']</value>
      <webElementGuid>ed49711b-7e19-4bee-b0a1-98a5bb41fae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalAdd']/span/span/span[2]/ul</value>
      <webElementGuid>71a3fd15-9884-4d33-aca3-3800b1a23efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>de30664f-9298-4d8d-837b-4a21abc1860e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-picAdd-results' and (text() = 'Eric - igloanam - igloFachri eKreasi - igloRaihan - IndocyberYoga Wiranda - igloAdmin Indocyber - indocyberdevapi - igloakun dev - indocyberFachri iglo - igloStephen Strange - igloAkun Demo - demoadmin - igloKMS - kmsMaya Nurmalasari - democobaja - igloPUTRA DWI JULIANTO - igloAndre - indocyberakun - indocyberfurqan - igloBruce Banner - iglotabita iglo - igloeric - iglojean - jeaneric - igloErlan S - hahahihiBeby Romeo - demoDummy 02 - indocyberTabita - igloEric Yop - igloRobert Downey - igloBerliandika - indocyberAdmin Indocyber - igloKMS Indocyber - iglotest - igloEric Cantona - igloanam - igloTony Stark - igloshafrizal - iglotasya 2 - igloandre berliansyah - igloEric Yop - igloEric - iglocobaja - iglofurqan tes - ekreasicoba - igloTabita Iglo - igloAdmin - igloNovian Faisal - igloAdmin - igloAkun Indocyber - indocyberABBAS SALEH - iglofurqannn - igloTes Register Error - ahmad agus - 4hm4dTabita Id - demoEpul - igloeric - igloCoba register pake mobile - igloUpturn - DemoEmber - indocyberSahid Test - igloeKreasi - trialeric - igloDemo - fachri iglo - iglotestgalang - igloEGG - iglotasya - iglouser_test - igloEl Fachri - fachri ekf - igloFurqan AWJ - indocybersylvia - igloUser Demo - demofurqann - igloSahid R - iglofurqan - igloerlan - hahahihitestgalang - igloEric Yop - iglotasya - demoAndre Berlian - iglo' or . = 'Eric - igloanam - igloFachri eKreasi - igloRaihan - IndocyberYoga Wiranda - igloAdmin Indocyber - indocyberdevapi - igloakun dev - indocyberFachri iglo - igloStephen Strange - igloAkun Demo - demoadmin - igloKMS - kmsMaya Nurmalasari - democobaja - igloPUTRA DWI JULIANTO - igloAndre - indocyberakun - indocyberfurqan - igloBruce Banner - iglotabita iglo - igloeric - iglojean - jeaneric - igloErlan S - hahahihiBeby Romeo - demoDummy 02 - indocyberTabita - igloEric Yop - igloRobert Downey - igloBerliandika - indocyberAdmin Indocyber - igloKMS Indocyber - iglotest - igloEric Cantona - igloanam - igloTony Stark - igloshafrizal - iglotasya 2 - igloandre berliansyah - igloEric Yop - igloEric - iglocobaja - iglofurqan tes - ekreasicoba - igloTabita Iglo - igloAdmin - igloNovian Faisal - igloAdmin - igloAkun Indocyber - indocyberABBAS SALEH - iglofurqannn - igloTes Register Error - ahmad agus - 4hm4dTabita Id - demoEpul - igloeric - igloCoba register pake mobile - igloUpturn - DemoEmber - indocyberSahid Test - igloeKreasi - trialeric - igloDemo - fachri iglo - iglotestgalang - igloEGG - iglotasya - iglouser_test - igloEl Fachri - fachri ekf - igloFurqan AWJ - indocybersylvia - igloUser Demo - demofurqann - igloSahid R - iglofurqan - igloerlan - hahahihitestgalang - igloEric Yop - iglotasya - demoAndre Berlian - iglo')]</value>
      <webElementGuid>94bbf454-c63b-4dd2-8ca8-3a6f37fdd9d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
