<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Branch Kode Instansi Branch</name>
   <tag></tag>
   <elementGuidId>2070cc9f-e439-4e35-a2c9-9c051eca1265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kodeInstansiAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kodeInstansiAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0be483a7-acf2-443d-a030-fa6bbc849618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bf96881-f192-4b57-bbd0-8c0c9987e980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>88af83f3-a426-4ea0-8fa8-3072832518a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kodeInstansiAdd</value>
      <webElementGuid>c81462d6-3e64-4e25-9219-bb19ba518286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instanceCode</value>
      <webElementGuid>12fc881c-2801-45d5-be7c-81764f08d175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Instansi</value>
      <webElementGuid>52a851ad-244a-4c6b-908c-260646e4f0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>68f1a6b3-9898-47e7-ba64-98620608409d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kodeInstansiAdd&quot;)</value>
      <webElementGuid>12871b47-7b66-4191-8156-42ea0592e09f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kodeInstansiAdd']</value>
      <webElementGuid>f6a024c4-521d-4850-bc14-557b498084ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/input</value>
      <webElementGuid>67eb38cd-a8e1-4c46-989d-680df6be392e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>fba4991d-c603-486f-9907-d85423fd05b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kodeInstansiAdd' and @name = 'instanceCode' and @placeholder = 'Kode Instansi']</value>
      <webElementGuid>00caad9d-d650-44e7-858c-4d9bdd7d3086</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
