<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_value_2</name>
   <tag></tag>
   <elementGuidId>31a28d21-aa93-45f2-8ab0-7b7e967e6091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul/li[contains(text(),'ISO')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6fab0d1f-4eb2-46ec-bb76-a551c46f8d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1705997596688</value>
      <webElementGuid>f348b515-b8a8-48dd-bcce-127b073ca734</webElementGuid>
   </webElementProperties>
</WebElementEntity>
