<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn Module</name>
   <tag></tag>
   <elementGuidId>59fb90a5-21a4-4aba-ab51-540312514244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-moduleIdAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-moduleIdAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4169d27b-cb86-42fc-b08f-d4fc94ca7524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f3d90ec8-39db-4852-8071-9e4d4a02d3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-moduleIdAdd-container</value>
      <webElementGuid>9721e644-b30a-4e3e-8710-21613bf85a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose Module --</value>
      <webElementGuid>3b0a8b79-2cc5-426e-be99-80d7159a4f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-moduleIdAdd-container&quot;)</value>
      <webElementGuid>9597491f-f424-45b5-b66d-99dc53aaaa31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-moduleIdAdd-container']</value>
      <webElementGuid>04fa0bf0-e6bf-4af8-9b86-ae17af58940d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/span/span/span/span</value>
      <webElementGuid>5e83bcc3-dd7d-4db9-8352-bb830bef4815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>c8c6685d-cb58-42bc-a164-9eef973debfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-moduleIdAdd-container' and (text() = '-- Choose Module --' or . = '-- Choose Module --')]</value>
      <webElementGuid>0ae4122d-183a-44b1-87f0-130cd38b9e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
