<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_value</name>
   <tag></tag>
   <elementGuidId>971c5af3-7d16-425b-8c5e-f2f27cb1bfa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-levelIdAdd-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-levelIdAdd-results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>1266524a-de1c-4b44-bb92-af8fa55c8e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>d483938b-4166-4c4f-9cf4-fab443ca9e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tree</value>
      <webElementGuid>dee3d2b5-4734-4607-b94a-41e447eb546a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-levelIdAdd-results</value>
      <webElementGuid>ae3c3d04-809b-49f2-a711-5a89ec527ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7229793e-6738-4605-9155-62bb85c5204a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51f85d13-bba3-4ac1-ab76-b6b20497fe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4</value>
      <webElementGuid>fccac784-b042-4689-b321-a05382f63f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-levelIdAdd-results&quot;)</value>
      <webElementGuid>c38a3df6-41c0-4ac5-ac3e-f4712278a739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-levelIdAdd-results']</value>
      <webElementGuid>5bc59538-86c5-4c04-a4c6-cd6160d5cbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/span/span/span[2]/ul</value>
      <webElementGuid>829ff2d0-5e81-4e68-9fdd-3e728984b778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>02e25ff1-7989-4592-8b15-67184739b634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-levelIdAdd-results' and (text() = 'ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4' or . = 'ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4')]</value>
      <webElementGuid>5e736661-ae37-4c13-84cf-5a2cd73d078f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
