<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Branch PIC Raihan</name>
   <tag></tag>
   <elementGuidId>cfe300aa-921e-4611-b224-c6b174d7fadb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-picAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-picAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e6292bc-4be2-421e-a183-a33f66d73176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>8984d12a-876d-4764-b415-1bc0ae0dfe1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-picAdd-container</value>
      <webElementGuid>e9fb3e53-ce5c-477b-82d7-0bab843ea866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Raihan - Indocyber</value>
      <webElementGuid>77c5bb93-9467-4b05-a57d-821092ce1465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Raihan - Indocyber</value>
      <webElementGuid>9533897a-6ac6-47a5-a64a-d83f69550855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-picAdd-container&quot;)</value>
      <webElementGuid>cd083742-7c95-4884-99d8-107e5f4a9b90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-picAdd-container']</value>
      <webElementGuid>b51800b2-df6b-4384-b601-d5eec77c0de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/span/span/span/span</value>
      <webElementGuid>eedc1cb5-67f0-4aa5-bfd5-12cec91129a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>0adca5fe-47f0-4c62-9ce6-5f410d67b403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-picAdd-container' and @title = 'Raihan - Indocyber' and (text() = 'Raihan - Indocyber' or . = 'Raihan - Indocyber')]</value>
      <webElementGuid>99ccd5bb-95d5-49f1-b024-4fc10b1c9ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
