<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form 1 - system user</name>
   <tag></tag>
   <elementGuidId>527efa27-3b40-409b-a3da-4d143232eace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-background-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b5e3f40-a0fb-4f00-a4fe-8eac04d625b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-background-container</value>
      <webElementGuid>2d94fd02-584f-426f-84b4-88fe0531dcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>System UsersUsernameUser Role-- Select --Employee NameStatus-- Select -- Reset  Search  Add  (41) Records FoundUsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActionsAaliyah.HaqESSAaliyah HaqEnabledAdminAdminSaurabh thonnnEnabledAlice.DuvalESSAlice DuvalEnabledAnthony.NolanESSAnthony NolanEnabledCassidy.HopeESSCassidy HopeEnabledCecil.BonaparteESSCecil BonaparteEnabledCharlie.CarterESSCharlie CarterEnabledCheekuAdminVirat KohliEnabledChenzira.ChukiESSChenzira ChukiEnabledDavid.MorrisESSDavid MorrisEnabledDNVVBAdminCharlie CarterEnabledDominic.ChaseAdminDominic ChaseEnabledEhioze.EboESSEhioze EboEnabledFiona.GraceESSFiona GraceEnabledGarry.WhiteESSGarry WhiteEnabledGoutam.GaneshESSGoutam GaneshEnabledJacqueline.WhiteESSJacqueline WhiteEnabledJadine.JackieESSJadine JackieEnabledJasmine.MorganESSJasmine MorganEnabledJoe.RootESSJoe RootEnabledJohn.SmithAdminJohn SmithEnabledJordan.MathewsESSJordan MathewsEnabledKevin.MathewsESSKevin MathewsEnabledKiyara.HuESSKiyara HuEnabledkpkarthikESSkarthik PulipatiEnabledLinda.AndersonAdminLinda AndersonEnabledLisa.AndrewsESSLisa AndrewsEnabledLuke.WrightESSLuke WrightEnabledMaggie.ManningESSMaggie ManningEnabledMelan.PeirisESSMelan PeirisEnabledNathan.ElliotESSNathan ElliotEnabledNina.PatelESSNina PatelEnabledNYRtPHmpOfESSqxBQpeRmUM WrUAVcRNfdEnabledOdis.AdalwinAdminOdis AdalwinEnabledPeter.AndersonAdminPeter AndersonEnabledRaviTechESSRavi HariEnabledRebecca.HarmonyESSRebecca HarmonyEnabledRussel.HamiltonESSRussel HamiltonEnabledSania.ShaheenESSSania ShaheenEnabledSara.TencradyESSSara TencradyEnabledTest2AdminCharlie CarterEnabled</value>
      <webElementGuid>3c7bf624-3ca6-4fb6-a691-786d9d7ede1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]</value>
      <webElementGuid>73068493-035b-42a1-b9a4-a4cf022e9d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      <webElementGuid>109ac881-bb3d-4a54-9697-cd02e3495a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>d71c3c4e-a7bb-4db4-8632-0675ba63673f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'System UsersUsernameUser Role-- Select --Employee NameStatus-- Select -- Reset  Search  Add  (41) Records FoundUsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActionsAaliyah.HaqESSAaliyah HaqEnabledAdminAdminSaurabh thonnnEnabledAlice.DuvalESSAlice DuvalEnabledAnthony.NolanESSAnthony NolanEnabledCassidy.HopeESSCassidy HopeEnabledCecil.BonaparteESSCecil BonaparteEnabledCharlie.CarterESSCharlie CarterEnabledCheekuAdminVirat KohliEnabledChenzira.ChukiESSChenzira ChukiEnabledDavid.MorrisESSDavid MorrisEnabledDNVVBAdminCharlie CarterEnabledDominic.ChaseAdminDominic ChaseEnabledEhioze.EboESSEhioze EboEnabledFiona.GraceESSFiona GraceEnabledGarry.WhiteESSGarry WhiteEnabledGoutam.GaneshESSGoutam GaneshEnabledJacqueline.WhiteESSJacqueline WhiteEnabledJadine.JackieESSJadine JackieEnabledJasmine.MorganESSJasmine MorganEnabledJoe.RootESSJoe RootEnabledJohn.SmithAdminJohn SmithEnabledJordan.MathewsESSJordan MathewsEnabledKevin.MathewsESSKevin MathewsEnabledKiyara.HuESSKiyara HuEnabledkpkarthikESSkarthik PulipatiEnabledLinda.AndersonAdminLinda AndersonEnabledLisa.AndrewsESSLisa AndrewsEnabledLuke.WrightESSLuke WrightEnabledMaggie.ManningESSMaggie ManningEnabledMelan.PeirisESSMelan PeirisEnabledNathan.ElliotESSNathan ElliotEnabledNina.PatelESSNina PatelEnabledNYRtPHmpOfESSqxBQpeRmUM WrUAVcRNfdEnabledOdis.AdalwinAdminOdis AdalwinEnabledPeter.AndersonAdminPeter AndersonEnabledRaviTechESSRavi HariEnabledRebecca.HarmonyESSRebecca HarmonyEnabledRussel.HamiltonESSRussel HamiltonEnabledSania.ShaheenESSSania ShaheenEnabledSara.TencradyESSSara TencradyEnabledTest2AdminCharlie CarterEnabled' or . = 'System UsersUsernameUser Role-- Select --Employee NameStatus-- Select -- Reset  Search  Add  (41) Records FoundUsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActionsAaliyah.HaqESSAaliyah HaqEnabledAdminAdminSaurabh thonnnEnabledAlice.DuvalESSAlice DuvalEnabledAnthony.NolanESSAnthony NolanEnabledCassidy.HopeESSCassidy HopeEnabledCecil.BonaparteESSCecil BonaparteEnabledCharlie.CarterESSCharlie CarterEnabledCheekuAdminVirat KohliEnabledChenzira.ChukiESSChenzira ChukiEnabledDavid.MorrisESSDavid MorrisEnabledDNVVBAdminCharlie CarterEnabledDominic.ChaseAdminDominic ChaseEnabledEhioze.EboESSEhioze EboEnabledFiona.GraceESSFiona GraceEnabledGarry.WhiteESSGarry WhiteEnabledGoutam.GaneshESSGoutam GaneshEnabledJacqueline.WhiteESSJacqueline WhiteEnabledJadine.JackieESSJadine JackieEnabledJasmine.MorganESSJasmine MorganEnabledJoe.RootESSJoe RootEnabledJohn.SmithAdminJohn SmithEnabledJordan.MathewsESSJordan MathewsEnabledKevin.MathewsESSKevin MathewsEnabledKiyara.HuESSKiyara HuEnabledkpkarthikESSkarthik PulipatiEnabledLinda.AndersonAdminLinda AndersonEnabledLisa.AndrewsESSLisa AndrewsEnabledLuke.WrightESSLuke WrightEnabledMaggie.ManningESSMaggie ManningEnabledMelan.PeirisESSMelan PeirisEnabledNathan.ElliotESSNathan ElliotEnabledNina.PatelESSNina PatelEnabledNYRtPHmpOfESSqxBQpeRmUM WrUAVcRNfdEnabledOdis.AdalwinAdminOdis AdalwinEnabledPeter.AndersonAdminPeter AndersonEnabledRaviTechESSRavi HariEnabledRebecca.HarmonyESSRebecca HarmonyEnabledRussel.HamiltonESSRussel HamiltonEnabledSania.ShaheenESSSania ShaheenEnabledSara.TencradyESSSara TencradyEnabledTest2AdminCharlie CarterEnabled')]</value>
      <webElementGuid>5407e616-56d7-4c82-9567-eab47d800e33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
