<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Screen Login</name>
   <tag></tag>
   <elementGuidId>261b1321-fb66-4b20-a23d-47442c624de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.login-half.login-bg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb2c3766-758e-42d1-883c-4217d77e5a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-half login-bg</value>
      <webElementGuid>69f7163d-462c-4435-820d-71b795187809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;login-wrapper&quot;]/div[@class=&quot;d-flex flex-row w-100&quot;]/div[@class=&quot;login-half login-bg&quot;]</value>
      <webElementGuid>abe26e87-ae5e-4157-a950-9be505c1cd86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>09fea5b6-7992-4874-a875-f03c0ed61744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
