<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InstanceCode</name>
   <tag></tag>
   <elementGuidId>d880d03a-98fb-4745-8363-6ffeb6167547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#instanceCodeAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='instanceCodeAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffab6290-fd79-493e-bf75-cf202274bd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee08c871-6691-4d36-820e-184be1415a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d616e629-b436-4fe9-8034-b053b62fab6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>instanceCodeAdd</value>
      <webElementGuid>b63b9bf7-ebc7-4710-b40d-69088253f518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instanceCode</value>
      <webElementGuid>7ccf4814-ae91-4f79-9db0-b77a6cf55d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Instance Code</value>
      <webElementGuid>b9b74f08-abce-47d5-b6ba-e96e543001fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>25170f22-37e7-4d0f-8eae-8ec1e139fa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>dfd7a22c-cfe0-4a70-9af1-3dfeeaf81564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;instanceCodeAdd&quot;)</value>
      <webElementGuid>cf83a97d-0ad8-4d26-979e-879a1900c4ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='instanceCodeAdd']</value>
      <webElementGuid>abbcb36d-40e5-4f14-a7cc-8a7ad786d5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/input</value>
      <webElementGuid>fe3c2a1c-74a0-445c-be49-fff194de692f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>d9840d2a-e352-4e65-9764-d2e261accc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'instanceCodeAdd' and @name = 'instanceCode' and @placeholder = 'Instance Code']</value>
      <webElementGuid>b484b3e0-52a0-4d3c-afbc-1514856bbfcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
