<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RSearch2</name>
   <tag></tag>
   <elementGuidId>bebde7f3-2f53-419f-8f25-6bb304377ec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'select2-roleAdd-result-wbja-ce07b050-a303-42e0-bd60-587661fcbf6d' and (text() = 'test' or . = 'test')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>72abdd1f-948b-41d1-bfb8-2d52d1ee50d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>b9437385-dcb4-4810-89a2-0d26e228628f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-roleAdd-result-wbja-ce07b050-a303-42e0-bd60-587661fcbf6d</value>
      <webElementGuid>ee62236d-9e4a-4c6a-b65f-e1f41c36656a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>d0a91dca-5105-4cac-833c-7005a3de6550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98e363ab-055d-4817-a930-6323d1098d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>81c74dab-6e4d-40fd-9b42-df76ec8f286f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;select2-container select2-container--default select2-container--open&quot;]/span[@class=&quot;select2-dropdown select2-dropdown--above&quot;]/span[@class=&quot;select2-results&quot;]/ul[@id=&quot;select2-roleAdd-results&quot;]/li[@id=&quot;select2-roleAdd-result-wbja-ce07b050-a303-42e0-bd60-587661fcbf6d&quot;]</value>
      <webElementGuid>676b647f-a9ca-4cb1-a45d-3ca971bebe10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-roleAdd-result-wbja-ce07b050-a303-42e0-bd60-587661fcbf6d' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>6134755a-b7ce-4ff7-885c-2c45cb47d343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
