<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chepvalue</name>
   <tag></tag>
   <elementGuidId>3d2029ac-71ee-4d84-876c-11dccb137d21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-chapterAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-chapterAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f0a5a40-7b46-48f7-8062-4974372d0fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a666e477-7f5e-4a0e-8513-883c82835598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-chapterAdd-container</value>
      <webElementGuid>c6ca276f-1637-43ac-bac3-73389aac0b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Materi 2</value>
      <webElementGuid>ad8f61d1-e3c6-42b1-bd0e-ac4a48e29f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Materi 2</value>
      <webElementGuid>c95b71d5-e75c-4d27-be94-53748e558bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-chapterAdd-container&quot;)</value>
      <webElementGuid>dc5777c9-208b-427d-9c10-4fbedde63144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-chapterAdd-container']</value>
      <webElementGuid>05a3b5ed-aa15-4c6b-bbde-b248c4a2065a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>7eb1414e-aa4c-4cde-ae03-84fb04158e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span/span/span</value>
      <webElementGuid>2bd28662-0834-488f-b588-c5b560859765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-chapterAdd-container' and @title = 'Materi 2' and (text() = '×Materi 2' or . = '×Materi 2')]</value>
      <webElementGuid>685b133b-be6d-419b-8ad0-fc16d766184e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
