<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Option A_optA</name>
   <tag></tag>
   <elementGuidId>fab9ccdb-676f-4e05-b689-c5fa86098cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optAAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optAAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c339dd4d-f3a8-4c2e-90a7-830ac0c5763f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>26b866aa-88bf-4e47-99bc-445583164e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optA</value>
      <webElementGuid>7f0033b6-8ddc-4231-ad46-ea82202a82a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optAAdd</value>
      <webElementGuid>9c222831-fd95-4689-b4dc-ab0cb52b6c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>84ad67b1-422c-4b4a-a098-38fbd1fcc0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option A</value>
      <webElementGuid>250ab012-9223-4d75-b8e1-a289160af346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>6b653cf3-89ec-416b-8b0a-9fa996f2fe4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optAAdd&quot;)</value>
      <webElementGuid>737a53a8-70fb-4217-87c0-879ac3a154db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optAAdd']</value>
      <webElementGuid>ceef66c9-98e9-4947-a595-fa60712f71a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[3]/div/div/textarea</value>
      <webElementGuid>59f9aa8c-26a2-4cfc-8fd3-0303e9ec10ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/textarea</value>
      <webElementGuid>0748d1d2-d70d-4f6f-84c9-55ae7822d105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optA' and @id = 'optAAdd' and @placeholder = 'Option A']</value>
      <webElementGuid>93cdfef4-1917-49b9-8ac6-ba372dbbbecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
