<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Option C_optC</name>
   <tag></tag>
   <elementGuidId>d73c289b-d995-4aba-aa0f-6bc7590e62e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optCAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optCAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c5ea1aa9-b19d-4417-abf8-284746706ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a1923e49-2fdd-4da5-8a0a-29d24f9c8d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optC</value>
      <webElementGuid>f708728b-6f93-4dc3-a074-570a04594c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optCAdd</value>
      <webElementGuid>0268f491-e3a0-4c5d-b296-057bb293187e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1c38ed35-7f7d-4904-b436-8fc8caa3203a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option C</value>
      <webElementGuid>781699f9-d085-418a-9394-d0bc817d9400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>d9c2bd7b-1dca-46aa-a446-b2e081d47e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optCAdd&quot;)</value>
      <webElementGuid>e1fc7a3a-c3c2-447b-8b40-0e3f50bba9a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optCAdd']</value>
      <webElementGuid>75926128-8b27-487f-861c-94cfe039e8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/div/div/textarea</value>
      <webElementGuid>49f7cb19-3439-426b-b52e-42890a1dec37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>07ee8b8b-a480-4f1a-ad6d-6847223d3bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optC' and @id = 'optCAdd' and @placeholder = 'Option C']</value>
      <webElementGuid>5921d1aa-58ba-4bce-b36b-3644b92bc77e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
