<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Option D_optD</name>
   <tag></tag>
   <elementGuidId>41b5de20-2089-4172-8170-f2488d75530d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optDAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='optDAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>529f72ea-fd5e-428a-a0ae-b4feae0b3546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>13c80027-2d0b-4b5f-a643-37baaed58330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optD</value>
      <webElementGuid>ffdd1e9f-672d-4b11-8fef-63da79734bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optDAdd</value>
      <webElementGuid>29c31cdd-ea93-4e54-b941-305cf0f5a700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e6d27cb4-2607-4daa-8ea5-ae0d19c14b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Option D</value>
      <webElementGuid>2d350664-1634-45d0-87f6-11b153d21d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>450</value>
      <webElementGuid>5d337d22-0522-44d4-80b6-06f5cdbb475a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optDAdd&quot;)</value>
      <webElementGuid>b5a8e3d6-283c-4d05-b530-8e92e3ae224f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='optDAdd']</value>
      <webElementGuid>c3338a3f-8b86-4c2c-b1cc-7dfe1ff0fa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[4]/div[2]/div/textarea</value>
      <webElementGuid>2eaa5261-9885-4573-a489-4298d36b568b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/textarea</value>
      <webElementGuid>9a5ac359-286e-4ead-9d61-e7a26dab7f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'optD' and @id = 'optDAdd' and @placeholder = 'Option D']</value>
      <webElementGuid>8e3b6631-25c5-4d7a-92c6-3c6c28072e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
