<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>valueModule (1)</name>
   <tag></tag>
   <elementGuidId>f8b12a5b-975f-4d1a-9c12-b53814369189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-moduleAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-moduleAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5bc5a28a-3f11-4a51-9230-7feb87c9cc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e3565f4a-babf-4d8a-850a-e5eb018e0015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-moduleAdd-container</value>
      <webElementGuid>7ac791e3-0f05-4591-82d0-f811abecd9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ISO 27001</value>
      <webElementGuid>9f57db05-7ce5-4f15-b6b3-3953210959b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×ISO 27001</value>
      <webElementGuid>96646be4-e3d4-499f-aea3-398974bcb336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-moduleAdd-container&quot;)</value>
      <webElementGuid>4607463b-acc7-4643-9fce-da76eae02e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-moduleAdd-container']</value>
      <webElementGuid>8cc5f444-19f6-4a69-8bb1-5bb02e6a5a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>61eda312-dac2-4b1e-a1b8-fa22ffb8661c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>0f3d6f4e-8fba-486e-97b7-4887809fa12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-moduleAdd-container' and @title = 'ISO 27001' and (text() = '×ISO 27001' or . = '×ISO 27001')]</value>
      <webElementGuid>e5f13a1d-7871-4ebe-b2b4-eec3e4cea843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
