<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>valueModule</name>
   <tag></tag>
   <elementGuidId>a5cd22ed-080e-48eb-af56-00d632be4797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-moduleAdd-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-moduleAdd-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>575c209b-91c4-490e-a255-7f9bb94656c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e85bee18-3283-4af8-a58e-f1fa0e9f21a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-moduleAdd-container</value>
      <webElementGuid>1e9eeb6c-d197-459e-a7f8-fc1ee11fdd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ISO 27001</value>
      <webElementGuid>920c7648-df16-4b2c-81db-5e355434289a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×ISO 27001</value>
      <webElementGuid>d2010f5c-8bfa-4201-9925-3896c057c3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-moduleAdd-container&quot;)</value>
      <webElementGuid>833af8d0-3871-413d-b4df-c187131be47b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-moduleAdd-container']</value>
      <webElementGuid>773069a1-8ddf-4a07-a6c7-c185e2b3587b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>ddff5051-8b1f-43c3-90d3-bdd954ac8547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/span/span</value>
      <webElementGuid>5e7298a5-4aba-4577-a765-fa0dafb82a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-moduleAdd-container' and @title = 'ISO 27001' and (text() = '×ISO 27001' or . = '×ISO 27001')]</value>
      <webElementGuid>b94c3867-c4d7-4457-b052-0b24305a00f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
